# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: osx
      before_install:
        - brew install libgit2
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
